version: '2'
services:
    feedme-app:
        image: feedme
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://feedme-postgresql:5432/feedme
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    feedme-postgresql:
        extends:
            file: postgresql.yml
            service: feedme-postgresql
